/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ithembaburialsociety;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setTitle("Ithemba Burial Society: Login");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        txtUsername.requestFocusInWindow();
    }
    
    static private int intUserLoginID = 0;
    static private Long lngPrincipalIDNumber;
    
    private final clsDatabaseProcedures databaseProcedures = new clsDatabaseProcedures();
    
    private final frmMainWindow frmMain = new frmMainWindow();
    
    public int mGetUserLoginID() {
        return intUserLoginID;
    }
    
    public void mSetUserLoginID(int intLoginID) {
        intUserLoginID = intLoginID;
    }
    
    public Long mGetPrincipalIDNumber() {
        return lngPrincipalIDNumber;
    }
    
    public void mSetPrincipalIDNumber(Long lngPrincipalIDNo) {
        lngPrincipalIDNumber = lngPrincipalIDNo;
    }
    
    private String mCheckInput() {
        if(txtUsername.getText().equals("") && txtPassword.getText().equals("")) {
            txtUsername.requestFocusInWindow();
            return "Username & Password required!";
            
        } else if(txtUsername.getText().equals("")) {
            txtUsername.requestFocusInWindow();
            return "Username is required!";
            
        } else if(txtPassword.getText().equals("")) {
            txtPassword.requestFocusInWindow();
            return "Password is required!";
        }
        return "";
    }
    
    private void mLoginUser() {
        if(mCheckInput().equals("")) {
            if(databaseProcedures.mCheckIfRecordExists("SELECT Username, Password FROM Users_Login WHERE Username ='"+
                        txtUsername.getText().trim()+"' AND Password ='"+txtPassword.getText().trim()
                                +"' AND Role ='"+cboRole.getSelectedItem().toString()+"'")){
                mSetUserLoginID(Integer.parseInt(databaseProcedures.mFieldValue("SELECT ID FROM Users_Login WHERE Username ='"+txtUsername.getText().trim()
                                +"' AND Password ='"+txtPassword.getText().trim()+
                                    "' AND Role ='"+cboRole.getSelectedItem().toString()+"'")));
                
                if(!databaseProcedures.mFieldValue("SELECT Role FROM Users_Login WHERE ID ="+intUserLoginID).equals("Administrator")) {
                    
                    mSetPrincipalIDNumber(databaseProcedures.mGetIDNumber("SELECT IDNum FROM Principal_Members WHERE Account ="+intUserLoginID));
                }
                frmMain.mSetAccessControl(databaseProcedures.mFieldValue("SELECT Role FROM Users_Login WHERE ID ="+intUserLoginID));
                frmMain.setVisible(true);
                this.dispose();
            } else if(txtUsername.getText().trim().equals("Oriana") && txtPassword.getText().trim().equals("4004785")
                    && cboRole.getSelectedItem().toString().equals("Administrator")) {
                frmMain.mSetAccessControl("");
                frmMain.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Login Credentials Incorrect!", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, mCheckInput(), "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktpLogin = new javax.swing.JDesktopPane();
        lblUsername = new javax.swing.JLabel();
        lblLoginHeading = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRole = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        btnNewAcc = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsktpLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        lblLoginHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginHeading.setText("Login");

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRole.setText("Role");

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User/Client", "Administrator" }));

        btnNewAcc.setBackground(new java.awt.Color(102, 255, 255));
        btnNewAcc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewAcc.setText("New Acc");
        btnNewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(102, 255, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(102, 255, 255));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        dsktpLogin.setLayer(lblUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(lblLoginHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(txtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(lblPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(lblRole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(cboRole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(btnNewAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpLogin.setLayer(btnExit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsktpLoginLayout = new javax.swing.GroupLayout(dsktpLogin);
        dsktpLogin.setLayout(dsktpLoginLayout);
        dsktpLoginLayout.setHorizontalGroup(
            dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpLoginLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dsktpLoginLayout.createSequentialGroup()
                        .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPassword)
                                .addComponent(lblUsername))
                            .addComponent(lblRole))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(cboRole, 0, 130, Short.MAX_VALUE)))
                    .addGroup(dsktpLoginLayout.createSequentialGroup()
                        .addComponent(btnNewAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsktpLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        dsktpLoginLayout.setVerticalGroup(
            dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLoginHeading)
                .addGap(40, 40, 40)
                .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(76, 76, 76)
                .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(dsktpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAcc)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpLogin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpLogin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        mLoginUser();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccActionPerformed
        frmUserAccount userAccount = new frmUserAccount("Add Account");
        dsktpLogin.add(userAccount);
        userAccount.setVisible(true);
    }//GEN-LAST:event_btnNewAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewAcc;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JDesktopPane dsktpLogin;
    private javax.swing.JLabel lblLoginHeading;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
